import LegalLayout from './LegalLayout';

export default function PrivacyPolicy() {
  return (
    <LegalLayout
      eyebrow="Legal"
      title="Privacy Policy"
      lastUpdated="September 21, 2026"
    >
      <section>
        <h2>Overview</h2>
        <p>
          Application Ledger is a personal, independently-run project for
          tracking job and internship applications. It is not operated by a
          registered company. This policy explains what data the app
          collects, how it is used, and how you can control it.
        </p>
        <p>
          <strong>[PLACEHOLDER: Operator / entity name and location, if you
          want one listed here.]</strong>
        </p>
      </section>

      <section>
        <h2>Information we collect</h2>
        <ul>
          <li>
            <strong>Account information:</strong> the email address and
            password you provide when registering. Passwords are hashed
            before storage — we never store or have access to your plaintext
            password.
          </li>
          <li>
            <strong>Application data you enter:</strong> company names,
            roles, application status, dates, locations, platforms, and any
            notes you add to your ledger.
          </li>
          <li>
            <strong>Technical data:</strong> standard server logs (such as
            request timestamps and error data) generated by our hosting
            provider for debugging and reliability purposes.
          </li>
        </ul>
        <p>We do not collect payment information, and there is no billing on this app.</p>
      </section>

      <section>
        <h2>How your information is used</h2>
        <p>Your data is used solely to operate the app for you, specifically to:</p>
        <ul>
          <li>Authenticate you and keep your account secure.</li>
          <li>Store and display the application data you enter in your ledger.</li>
          <li>Diagnose bugs and keep the service running.</li>
        </ul>
        <p>We do not sell your data, and we do not use it for advertising.</p>
      </section>

      <section>
        <h2>How your information is stored</h2>
        <p>
          Application data is stored in a PostgreSQL database hosted via{' '}
          <a href="https://render.com" target="_blank" rel="noreferrer noopener">
            Render
          </a>
          , our infrastructure provider. When you log in, you receive a
          signed access token (JWT) that is stored in your browser's{' '}
          <code>localStorage</code> — not in a cookie — and sent with each
          request to authenticate you. See our{' '}
          <a href="/cookie-policy">Cookie Policy</a> for more detail on
          browser storage.
        </p>
      </section>

      <section>
        <h2>Demo account</h2>
        <p>
          The "Try the demo" option logs you into a single shared demo
          account. Data entered while using the demo account is visible to,
          and may be edited or reset by, anyone else using the demo. Do not
          enter real or sensitive information into the demo account.
        </p>
      </section>

      <section>
        <h2>Third parties</h2>
        <p>
          The app currently loads web fonts from Google Fonts. Loading these
          fonts may cause your browser to make a request to Google's
          servers, which can process your IP address as part of serving
          that request. No analytics or advertising trackers are currently
          in use.{' '}
          <strong>
            [PLACEHOLDER: update this section if analytics, error-tracking,
            or other third-party services are added later.]
          </strong>
        </p>
      </section>

      <section>
        <h2>Your choices</h2>
        <ul>
          <li>You can edit or delete any application entry you've created at any time.</li>
          <li>
            You can request deletion of your account and associated data by
            contacting us — see <a href="/contact">Contact</a>.
          </li>
        </ul>
      </section>

      <section>
        <h2>Changes to this policy</h2>
        <p>
          This policy may be updated as the app evolves. Material changes
          will be reflected by updating the "Last updated" date above.
        </p>
      </section>

      <section>
        <h2>Contact</h2>
        <p>
          Questions about this policy or your data can be sent to{' '}
          <strong>[PLACEHOLDER: contact email]</strong>, or via the{' '}
          <a href="/contact">Contact page</a>.
        </p>
      </section>
    </LegalLayout>
  );
}
